### ISSUE TITLE
My LCD is reversed

### ISSUE THREAD

**Issue by hunar1997** [arkroan/CT1642#1]
Hi, i found a similar circuit in a satellite receiver and i found your library when i asked a question [here](https://www.reddit.com/r/arduino/comments/7pftpa/how_to_use_this_with_arduini_i_found_this_in_a/) .. my chip is CT1642 02AH411 .. your library works but in reverse, so 1234 is displayed as 4321 in the display, 1 is displayed as 1000, text is also ERR1 becomes 1RRE, how can i reverse it i don't completely understand codes XD can you make your library support reversing :D, the circuit also have two LEDs, can i turn them on with this library?

**Comment by arkroan** [comment]
Hi,

It has been a while since I have used Arduino and this chip. Actually this library was the last thing I did with the Arduino. 
I do not have the Arduino and this chip/pcb anymore and I had to read my code again to remember what I have done and why.

I think if you locate the following function 
> byte CT1642::getDigitAddress(int digitNo)

you can swap the ordering of the 7segment displays like this:
```cpp
case 1: { 
	// 00:0X
	// 0xef = DEC-239, BIN-11101111
	digit = 0xef;
	break;
  }
case 2: { 
	// 00:X0
	// 0xdf = DEC-223, BIN-11011111
	digit = 0xdf;
	break;
  }
case 3: { 
	// 0X:00
	// 0xbf = DEC-191, BIN-10111111
	digit = 0xbf;
	break;
  }
case 4: { 
	// X0:00
	// 0x7f = DEC-127, BIN-B01111111
	digit = 0x7f;
	break;
  } 
```
Replace the code in the function for cases 1-4 with the above code.

I hope this will help. Unfortunately I will not be able to provide anything more than that.
Take some time to read through the code and start experimenting and I am sure you will understand a lot more.
